name: Build
on: [push, pull_request, workflow_dispatch]

jobs:
  build_on_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn make
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Linux
          path: out/make

  build_on_mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn make
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MacOS
          path: out/make

  build_on_win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn make
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windows
          path: out/make